CREATE TABLE `Admission` (
  `ID` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `PatientID` INT(11) DEFAULT NULL,
  `DoctorID` INT(11) DEFAULT NULL,
  `NurseID` INT(11) DEFAULT NULL,
  `StartDate` DATE DEFAULT NULL,
  `EndDate` DATE DEFAULT NULL,
  `RoomNumber` INT(11) DEFAULT NULL,
  `Reason` VARCHAR(255) DEFAULT NULL
);

CREATE TABLE `Appointment` (
  `PatientID` INT(11) NOT NULL,
  `DoctorID` INT(11) NOT NULL,
  `Date` DATETIME NOT NULL
);

CREATE TABLE `Department` (
  `ID` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) DEFAULT NULL
);

CREATE TABLE `Employee` (
  `ID` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) DEFAULT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  `firstName` VARCHAR(255) DEFAULT NULL,
  `lastName` VARCHAR(255) DEFAULT NULL,
  `type` VARCHAR(255) NOT NULL,
  `departmentID` INT(11) NOT NULL,
  `contactNumber` VARCHAR(255) DEFAULT NULL
);

CREATE TABLE `Medication` (
  `ID` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `PatientID` INT(11) DEFAULT NULL,
  `DoctorID` INT(11) DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Dosage` VARCHAR(255) DEFAULT NULL,
  `Frequency` TEXT DEFAULT NULL,
  `StartDate` DATE DEFAULT NULL,
  `EndDate` DATE DEFAULT NULL,
  `OtherDescription` TEXT DEFAULT NULL
);

CREATE TABLE `Patient` (
  `ID` INT(11) PRIMARY KEY NOT NULL,
  `FirstName` VARCHAR(255) DEFAULT NULL,
  `LastName` VARCHAR(255) DEFAULT NULL,
  `DateOfBirth` DATE DEFAULT NULL,
  `Gender` VARCHAR(255) DEFAULT NULL,
  `ContactNumber` VARCHAR(255) DEFAULT NULL,
  `EmailAddress` VARCHAR(255) DEFAULT NULL,
  `Address` VARCHAR(255) DEFAULT NULL
);

CREATE TABLE `Room` (
  `RoomNumber` INT(11) PRIMARY KEY NOT NULL,
  `DepartmentID` INT(11) NOT NULL
);

ALTER TABLE `Admission` ADD FOREIGN KEY (`PatientID`) REFERENCES `Patient` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Admission` ADD FOREIGN KEY (`DoctorID`) REFERENCES `Employee` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Admission` ADD FOREIGN KEY (`NurseID`) REFERENCES `Employee` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Admission` ADD FOREIGN KEY (`RoomNumber`) REFERENCES `Room` (`RoomNumber`) ON DELETE CASCADE;

ALTER TABLE `Appointment` ADD FOREIGN KEY (`PatientID`) REFERENCES `Patient` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Appointment` ADD FOREIGN KEY (`DoctorID`) REFERENCES `Employee` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Employee` ADD FOREIGN KEY (`departmentID`) REFERENCES `Department` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Medication` ADD FOREIGN KEY (`PatientID`) REFERENCES `Patient` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Medication` ADD FOREIGN KEY (`DoctorID`) REFERENCES `Employee` (`ID`) ON DELETE CASCADE;

ALTER TABLE `Room` ADD FOREIGN KEY (`DepartmentID`) REFERENCES `Department` (`ID`) ON DELETE CASCADE;